# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-21 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='from_area',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='from_area', to='simulator.Area'),
        ),
        migrations.AddField(
            model_name='airline',
            name='to_area',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='to_area', to='simulator.Area'),
        ),
        migrations.AlterField(
            model_name='airline',
            name='arrival',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='airline',
            name='departure',
            field=models.DateField(),
        ),
    ]
